### ISSUE TITLE
Why data/train.scp has same features in meeting EN2001a, EN2001d, EN2001e ?

### ISSUE THREAD

**Issue by gogyzzz** [FlorianKrey/DNC#3]
I have found that EN2001a, EN2001d, and EN2001e meeting utterances have four times the features of the original.

Why is it like this?

```python
from kaldiio import ReadHelper

feats = []
with ReadHelper('scp:data/train.scp') as reader:
    for key, numpy_array in reader:
        #if "0007881_0007913" in key:
        if "0056607_0056837" in key:
            print(key)
            feats.append(numpy_array)

#AMIXXX-00001-1EN2001a-XXXXXX-11_XXXXXXX_0056607_0056837
#AMIXXX-00001-3EN2001a-XXXXXX-11_XXXXXXX_0056607_0056837
#AMIXXX-00001-4EN2001a-XXXXXX-11_XXXXXXX_0056607_0056837
#AMIXXX-00001-5EN2001a-XXXXXX-11_XXXXXXX_0056607_0056837
```

```python
print(np.array_equal(feats[0], feats[1]))
print(np.array_equal(feats[1], feats[2]))
print(np.array_equal(feats[2], feats[3]))

#True
#True
#True
```

**Comment by FlorianKrey** [comment]
Hi @gogyzzz, as written in the paper we constrain all of our training meetings to contain 4 speakers. "Since we limit the number of speakers to 4, each of the 3 five-speaker meetings is duplicated into 5 four-speaker meetings
by removing one speaker at a time, which yields 147 meetings."
This causes those meetings to have overlap in the features because they correspond to the same speaker at the same time-spot in the meeting. The meeting you found is one of those five-speaker meetings.
